defaults: &defaults
  zhangbens: 
    zhangben1:
      name: 日常支出
      fenleis_attributes: [{name: 餐饮}, {name: 房租}, {name: 交通}, {name: 其他}]

    zhangben2:
      name: 借入借出
      fenleis_attributes: [{name: 借出}, {name: 借入}]

    zhangben3:
      name: 其他
      fenleis_attributes: [{name: 其他}]





development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
